sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.216331, 0.91]
      rpy: [0, 0, 'pi']
  break_beam_2:
    type: break_beam
    pose:
      # xyz: [1.6, 0.926964, 0.91]
      xyz: [1.6, 1.818089, 0.91]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.95, 2.6, 0.92]
      rpy: [0, 0, 0]
  lc_belt:
    type: logical_camera
    pose:
      xyz: [1.524540, 2.0, 1.218966]
      rpy: [-3.130727, 0.934865, -3.117780]
  lc_gear:
    type: logical_camera
    pose:
      xyz: [-0.652396, -0.385455, 0.974256]
      rpy: [-0.009386, 0.806891, 0.008639]
  lc_bin_1:
    type: logical_camera
    pose:
      xyz: [-0.652396, 1.912097, 0.974256]
      rpy: [-0.009386, 0.806891, 0.008639]
  lc_agv_1:
    type: logical_camera
    pose:
      xyz: [0.612581, 3.194624, 1.074704]
      rpy: [-3.138000, 0.944346, -3.139879]
  #      xyz: [0.308333, 3.445912, 1.134402]
  #      rpy: [-1.599666, 1.129617, -1.607519]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.6]
      rpy: ['-pi', 'pi/2', 'pi/2']
